afterInstall: yarn postinstall

compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js'
  - checksum: c24caac549e78ade14e6bb457b42dcfffd86c2f49fd24f94f041349cebf74a46a5667be6a7aa71d0a7eb2b4dded01322b903e230cefeb8cc7ded514be7a0b427
    path: .yarn/plugins/@yarnpkg/plugin-validate-install.cjs
    spec: plugin-validate-install.cjs
  - checksum: b586930db79bd4cab40bdf7804848fe8414c3e3bb4fe1347b7d1d1799db3b7f2219066796e9abeb33e452d745405401e2d43802883e017ff3b2973566b2484d9
    path: .yarn/plugins/@yarnpkg/plugin-peer-dependency.cjs
    spec: plugin-peer-resolutions.js

validateInstall: yarn validateinstall

yarnPath: .yarn/releases/yarn-4.2.2.cjs
