//
// DO NOT EDIT! This is an autogenerated file.
//

import enCommon from 'src/i18n/resources/en/common.json';
import jpCommon from 'src/i18n/resources/jp/common.json';
import vnCommon from 'src/i18n/resources/vn/common.json';

const resources = {
  en: {
    common: enCommon,
  },
  jp: {
    common: jpCommon,
  },
  vn: {
    common: vnCommon,
  },
};

export default resources;
