//
// DO NOT EDIT! This is an autogenerated file.
//

import enCommon from './resources/en/common.json';
import jpCommon from './resources/jp/common.json';
import vnCommon from './resources/vn/common.json';

const resources = {
  en: {
    common: enCommon,
  },
  jp: {
    common: jpCommon,
  },
  vn: {
    common: vnCommon,
  },
};

export default resources;
