const fs = require('fs');
const path = require('path');

const imageExts = ['.png', '.jpg', '.jpeg', '.bmp', '.gif', '.webp'];

const imageDirectory = path.join(__dirname, '../../src/assets/images');
const imageContentFile = path.join(__dirname, '../../src/assets/images.ts');

const importImages = () => {
  fs.readdir(imageDirectory, function (err, files) {
    if (err) {
      return console.log('Unable to scan image directory: ' + err);
    }

    files.sort();

    let imageContent = `//
// DO NOT EDIT! This is an autogenerated file.
//

`;

    files.forEach(function (file) {
      if (imageExts.find(ext => file.endsWith(ext))) {
        imageContent += `import ${toVariableName(
          path.parse(file).name,
        )} from 'src/assets/images/${file}';\n`;
      }
    });

    imageContent += '\nexport const IMAGES = {\n';

    files.forEach(function (file) {
      if (imageExts.find(ext => file.endsWith(ext))) {
        imageContent += `  ${toVariableName(path.parse(file).name)},\n`;
      }
    });

    imageContent += '};\n';

    fs.writeFile(imageContentFile, imageContent, function (err) {
      if (err) {
        return console.log('Error writing image file: ' + err);
      }

      console.log('Image file generated successfully!');
    });
  });
};

const toVariableName = str => {
  let first = true;
  const res = str.replace(/([_\- ]*)(.+?)(?=[_\- ]|$)/g, (_, _m1, letter) => {
    let newLetter;
    if (first) {
      newLetter = letter.replaceAll(/([^a-zA-z0-9]+)|(^[0-9]+)/g, '');
      first = false;
    } else {
      newLetter = capitalizeFirstLetter(letter.replaceAll(/[^a-zA-z0-9]+/g, ''));
    }

    return newLetter;
  });

  return res;
};

function capitalizeFirstLetter(string) {
  return string.length ? string.charAt(0).toUpperCase() + string.slice(1) : '';
}

module.exports = {
  dir: imageDirectory,
  importFn: importImages,
};
