const fs = require('fs');
const path = require('path');

const iconDirectory = path.join(__dirname, '../../src/assets/icons');
const iconContentFile = path.join(__dirname, '../../src/assets/icons.ts');

const importIcons = () => {
  fs.readdir(iconDirectory, function (err, files) {
    if (err) {
      return console.log('Unable to scan icon directory: ' + err);
    }

    files.sort();

    let iconContent = `//
// DO NOT EDIT! This is an autogenerated file.
//
/* eslint-disable max-lines */
`;

    files.forEach(function (file) {
      if (file.endsWith('.svg')) {
        iconContent += `import ${toVariableName(
          path.parse(file).name,
        )} from 'src/assets/icons/${file}';\n`;
      }
    });

    iconContent += '\nexport const ICONS = {\n';

    files.forEach(function (file) {
      if (file.endsWith('.svg')) {
        iconContent += `  ${toVariableName(path.parse(file).name)},\n`;
      }
    });

    iconContent += '};\n';

    fs.writeFile(iconContentFile, iconContent, function (err) {
      if (err) {
        return console.log('Error writing icon file: ' + err);
      }

      console.log('Icon file generated successfully!');
    });
  });
};

const toVariableName = str => {
  let first = true;
  const res = str.replace(/([_\- ]*)(.+?)(?=[_\- ]|$)/g, (_, _m1, letter) => {
    let newLetter;
    if (first) {
      newLetter = letter.replaceAll(/([^a-zA-z0-9]+)|(^[0-9]+)/g, '');
      first = false;
    } else {
      newLetter = capitalizeFirstLetter(letter.replaceAll(/[^a-zA-z0-9]+/g, ''));
    }

    return newLetter;
  });

  return res;
};

function capitalizeFirstLetter(string) {
  return string.length ? string.charAt(0).toUpperCase() + string.slice(1) : '';
}

module.exports = {
  dir: iconDirectory,
  importFn: importIcons,
};
