const fs = require('fs');
const path = require('path');

const resourceDirectory = path.join(__dirname, '../../src/i18n/resources/');
const resourceContentFile = path.join(__dirname, '../../src/i18n/resources.ts');

const importLanguages = () => {
  fs.readdir(resourceDirectory, { withFileTypes: true }, function (err, dirs) {
    if (err) {
      return console.log('Unable to scan language resource directory: ' + err);
    }

    dirs = dirs.filter(dir => dir.isDirectory());
    dirs.sort();

    let languageContent = `//
// DO NOT EDIT! This is an autogenerated file.
//

`;

    for (const dir of dirs) {
      const files = fs.readdirSync(path.join(dir.path, dir.name));
      if (!files.length) continue;

      files.sort();

      files.forEach(function (file) {
        if (file.endsWith('.json')) {
          languageContent += `import ${toVariableName(
            dir.name + '_' + path.parse(file).name,
          )} from 'src/i18n/resources/${dir.name}/${file}';\n`;
        }
      });
    }

    languageContent += '\nconst resources = {\n';

    for (const dir of dirs) {
      const files = fs.readdirSync(path.join(dir.path, dir.name));
      if (!files.length) continue;

      files.sort();

      languageContent += `  ${dir.name}: {\n`;

      files.forEach(function (file) {
        if (file.endsWith('.json')) {
          languageContent += `    ${path.parse(file).name}: ${toVariableName(dir.name + '_' + path.parse(file).name)},\n`;
        }
      });

      languageContent += '  },\n';
    }

    languageContent += '};\n\n';
    languageContent += 'export default resources;\n';

    fs.writeFile(resourceContentFile, languageContent, function (err) {
      if (err) {
        return console.log('Error writing language resource file: ' + err);
      }

      console.log('Language resource file generated successfully!');
    });
  });
};

const toVariableName = str => {
  let first = true;
  const res = str.replace(/([_\- ]*)(.+?)(?=[_\- ]|$)/g, (_, _m1, letter) => {
    let newLetter;
    if (first) {
      newLetter = letter.replaceAll(/([^a-zA-z0-9]+)|(^[0-9]+)/g, '');
      first = false;
    } else {
      newLetter = capitalizeFirstLetter(letter.replaceAll(/[^a-zA-z0-9]+/g, ''));
    }

    return newLetter;
  });

  return res;
};

function capitalizeFirstLetter(string) {
  return string.length ? string.charAt(0).toUpperCase() + string.slice(1) : '';
}

module.exports = {
  dir: resourceDirectory,
  importFn: importLanguages,
};
