require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true

platform :ios, '13.4'
prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

use_frameworks! :linkage => :static

abstract_target 'TConnectCommonPods' do
  target 'TConnect' do
    pod 'PromiseKit'
    pod 'IDZSwiftCommonCrypto'
    pod 'SnapKit'
    pod 'GoogleMLKit/FaceDetection'
    pod 'GoogleMLKit/TextRecognition'
    pod 'GoogleMLKit/TextRecognitionJapanese'
    pod 'SVProgressHUD'
  end

  target 'TConnectDev' do
    pod 'PromiseKit'
    pod 'IDZSwiftCommonCrypto'
    pod 'SnapKit'
    pod 'GoogleMLKit/FaceDetection'
    pod 'GoogleMLKit/TextRecognition'
    pod 'GoogleMLKit/TextRecognitionJapanese'
    pod 'SVProgressHUD'
  end

  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TConnectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["DEVELOPMENT_TEAM"] = "LR242TM46A"
        end
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.4
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        end
      end
    end
  end
end
