//
// DO NOT EDIT! This is an autogenerated file.
//
/* eslint-disable max-lines */
import accountOff from 'src/assets/icons/account-off.svg';
import accountOn from 'src/assets/icons/account-on.svg';
import appleIcon from 'src/assets/icons/apple-icon.svg';
import back from 'src/assets/icons/back.svg';
import changePassword from 'src/assets/icons/change-password.svg';
import checkboxChecked from 'src/assets/icons/checkbox-checked.svg';
import checkboxUnchecked from 'src/assets/icons/checkbox-unchecked.svg';
import circleClose from 'src/assets/icons/circle-close.svg';
import date from 'src/assets/icons/date.svg';
import dowVec from 'src/assets/icons/dow-vec.svg';
import editPersonalInfo from 'src/assets/icons/edit-personal-info.svg';
import email from 'src/assets/icons/email.svg';
import enIcon from 'src/assets/icons/en-icon.svg';
import eyeClosed from 'src/assets/icons/eye-closed.svg';
import eye from 'src/assets/icons/eye.svg';
import facebookIcon from 'src/assets/icons/facebook-icon.svg';
import fullname from 'src/assets/icons/fullname.svg';
import googleIcon from 'src/assets/icons/google-icon.svg';
import homeOff from 'src/assets/icons/home-off.svg';
import homeOn from 'src/assets/icons/home-on.svg';
import jpIcon from 'src/assets/icons/jp-icon.svg';
import language from 'src/assets/icons/language.svg';
import nextFirst from 'src/assets/icons/next-first.svg';
import nextSecond from 'src/assets/icons/next-second.svg';
import nextThird from 'src/assets/icons/next-third.svg';
import noImage from 'src/assets/icons/no-image.svg';
import othersOff from 'src/assets/icons/others-off.svg';
import othersOn from 'src/assets/icons/others-on.svg';
import phoneNumber from 'src/assets/icons/phone-number.svg';
import radioChecked from 'src/assets/icons/radio-checked.svg';
import radioUnchecked from 'src/assets/icons/radio-unchecked.svg';
import registerCheck from 'src/assets/icons/register-check.svg';
import rightVec from 'src/assets/icons/right-vec.svg';
import termsOfService from 'src/assets/icons/terms-of-service.svg';
import userGuide from 'src/assets/icons/user-guide.svg';
import vnIcon from 'src/assets/icons/vn-icon.svg';

export const ICONS = {
  accountOff,
  accountOn,
  appleIcon,
  back,
  changePassword,
  checkboxChecked,
  checkboxUnchecked,
  circleClose,
  date,
  dowVec,
  editPersonalInfo,
  email,
  enIcon,
  eyeClosed,
  eye,
  facebookIcon,
  fullname,
  googleIcon,
  homeOff,
  homeOn,
  jpIcon,
  language,
  nextFirst,
  nextSecond,
  nextThird,
  noImage,
  othersOff,
  othersOn,
  phoneNumber,
  radioChecked,
  radioUnchecked,
  registerCheck,
  rightVec,
  termsOfService,
  userGuide,
  vnIcon,
};
