//
// DO NOT EDIT! This is an autogenerated file.
//
/* eslint-disable max-lines */
import en from 'src/assets/icons/en-icon.svg';
import jp from 'src/assets/icons/jp-icon.svg';
import vn from 'src/assets/icons/vn-icon.svg';
import checkboxChecked from 'src/assets/icons/checkbox-checked.svg';
import checkboxUnchecked from 'src/assets/icons/checkbox-unchecked.svg';
import radioChecked from 'src/assets/icons/radio-checked.svg';
import radioUnchecked from 'src/assets/icons/radio-unchecked.svg';
import eyeClosed from 'src/assets/icons/eye-closed.svg';
import eye from 'src/assets/icons/eye.svg';
import noImage from 'src/assets/icons/no-image.svg';
import nF from 'src/assets/icons/next-first.svg';
import nS from 'src/assets/icons/next-second.svg';
import nT from 'src/assets/icons/next-third.svg';
import dowVec from 'src/assets/icons/dow-vec.svg';

export const ICONS = {
  en,
  jp,
  vn,
  checkboxChecked,
  checkboxUnchecked,
  radioChecked,
  radioUnchecked,
  noImage,
  eyeClosed,
  eye,
  dowVec,
  nF,
  nS,
  nT,
};
