//
// DO NOT EDIT! This is an autogenerated file.
//
/* eslint-disable max-lines */
import accountInfo from 'src/assets/icons/account-info.svg';
import addContract from 'src/assets/icons/add-contract.svg';
import addOutlineGrey from 'src/assets/icons/add-outline-grey.svg';
import addOutline from 'src/assets/icons/add-outline.svg';
import addPic from 'src/assets/icons/add-pic.svg';
import additionalInfo from 'src/assets/icons/additional-info.svg';
import arrowUp from 'src/assets/icons/arrow-up.svg';
import au from 'src/assets/icons/au.svg';
import avatarEdit from 'src/assets/icons/avatar-edit.svg';
import bronzeMember from 'src/assets/icons/bronze-member.svg';
import calendar from 'src/assets/icons/calendar.svg';
import camera from 'src/assets/icons/camera.svg';
import cancelOrder from 'src/assets/icons/cancel-order.svg';
import cardCornerWide from 'src/assets/icons/card-corner-wide.svg';
import cardCorner from 'src/assets/icons/card-corner.svg';
import cart from 'src/assets/icons/cart.svg';
import ccGi from 'src/assets/icons/cc-gi.svg';
import changePassword from 'src/assets/icons/change-password.svg';
import changePaymentMethod from 'src/assets/icons/change-payment-method.svg';
import checkDataCapacity from 'src/assets/icons/check-data-capacity.svg';
import checkNetworkSpeed from 'src/assets/icons/check-network-speed.svg';
import checkV from 'src/assets/icons/check-v.svg';
import check from 'src/assets/icons/check.svg';
import checkboxChecked from 'src/assets/icons/checkbox-checked.svg';
import checkboxUnchecked from 'src/assets/icons/checkbox-unchecked.svg';
import chevronDownAlt from 'src/assets/icons/chevron-down-alt.svg';
import chevronDown from 'src/assets/icons/chevron-down.svg';
import chevronLeft from 'src/assets/icons/chevron-left.svg';
import chevronRightAlt from 'src/assets/icons/chevron-right-alt.svg';
import chevronRight from 'src/assets/icons/chevron-right.svg';
import circlePlus from 'src/assets/icons/circle-plus.svg';
import clarityListLine from 'src/assets/icons/clarity-list-line.svg';
import clipboard from 'src/assets/icons/clipboard.svg';
import closeGray from 'src/assets/icons/close-gray.svg';
import closeRound from 'src/assets/icons/close-round.svg';
import closeWhite from 'src/assets/icons/close-white.svg';
import cod from 'src/assets/icons/cod.svg';
import combini from 'src/assets/icons/combini.svg';
import contactSupportPersonal from 'src/assets/icons/contact-support-personal.svg';
import contactSupport from 'src/assets/icons/contact-support.svg';
import contact from 'src/assets/icons/contact.svg';
import contractOutline from 'src/assets/icons/contract-outline.svg';
import contract from 'src/assets/icons/contract.svg';
import counter from 'src/assets/icons/counter.svg';
import creditLogo from 'src/assets/icons/credit-logo.svg';
import credit from 'src/assets/icons/credit.svg';
import dataCharge from 'src/assets/icons/data-charge.svg';
import dcom from 'src/assets/icons/dcom.svg';
import deleteAccount from 'src/assets/icons/delete-account.svg';
import diamondMember from 'src/assets/icons/diamond-member.svg';
import docomo from 'src/assets/icons/docomo.svg';
import doneSelected from 'src/assets/icons/done-selected.svg';
import doneUnselected from 'src/assets/icons/done-unselected.svg';
import dotSee from 'src/assets/icons/dot-see.svg';
import dotsHorizontal from 'src/assets/icons/dots-horizontal.svg';
import dots from 'src/assets/icons/dots.svg';
import dowVec from 'src/assets/icons/dow-vec.svg';
import downloadConfig from 'src/assets/icons/download-config.svg';
import download from 'src/assets/icons/download.svg';
import dropdowTai from 'src/assets/icons/dropdow-tai.svg';
import editable from 'src/assets/icons/editable.svg';
import epWarnTriangleFilled from 'src/assets/icons/ep-warn-triangle-filled.svg';
import esimBig from 'src/assets/icons/esim-big.svg';
import esim from 'src/assets/icons/esim.svg';
import eventGift from 'src/assets/icons/event-gift.svg';
import eyeClosed from 'src/assets/icons/eye-closed.svg';
import eye from 'src/assets/icons/eye.svg';
import faceScanOverlay from 'src/assets/icons/face-scan-overlay.svg';
import feNoticePush from 'src/assets/icons/fe-notice-push.svg';
import female from 'src/assets/icons/female.svg';
import flashOn from 'src/assets/icons/flash-on.svg';
import fluentDataPie20Regular from 'src/assets/icons/fluent-data-pie-20-regular.svg';
import fluentOptions48Filled from 'src/assets/icons/fluent-options-48-filled.svg';
import fluentTableSimpleInclude16Regular from 'src/assets/icons/fluent-table-simple-include-16-regular.svg';
import ggList from 'src/assets/icons/gg-list.svg';
import goldMember from 'src/assets/icons/gold-member.svg';
import gridLayout from 'src/assets/icons/grid-layout.svg';
import history from 'src/assets/icons/history.svg';
import home from 'src/assets/icons/home.svg';
import iconParkOutlinePaperMoney from 'src/assets/icons/icon-park-outline-paper-money.svg';
import iconPointPayment from 'src/assets/icons/icon-point-payment.svg';
import icons8Plus from 'src/assets/icons/icons8-plus.svg';
import image from 'src/assets/icons/image.svg';
import infinity from 'src/assets/icons/infinity.svg';
import info from 'src/assets/icons/info.svg';
import invite from 'src/assets/icons/invite.svg';
import ionFilter from 'src/assets/icons/ion-filter.svg';
import jpBank from 'src/assets/icons/jp-bank.svg';
import languageChecked from 'src/assets/icons/language-checked.svg';
import languageUnchecked from 'src/assets/icons/language-unchecked.svg';
import language from 'src/assets/icons/language.svg';
import law from 'src/assets/icons/law.svg';
import letsIconsCreditCard from 'src/assets/icons/lets-icons-credit-card.svg';
import linkOut from 'src/assets/icons/link-out.svg';
import listLayout from 'src/assets/icons/list-layout.svg';
import location from 'src/assets/icons/location.svg';
import logOut from 'src/assets/icons/log-out.svg';
import majesticonsDataPlusLine from 'src/assets/icons/majesticons-data-plus-line.svg';
import male from 'src/assets/icons/male.svg';
import managePaymentMethods from 'src/assets/icons/manage-payment-methods.svg';
import materialSymbolsCampaignOutlineRounded from 'src/assets/icons/material-symbols-campaign-outline-rounded.svg';
import materialSymbolsCardMembershipOutline from 'src/assets/icons/material-symbols-card-membership-outline.svg';
import materialSymbolsDeleteOutline from 'src/assets/icons/material-symbols-delete-outline.svg';
import materialSymbolsMarkChatUnreadOutlineRounded from 'src/assets/icons/material-symbols-mark-chat-unread-outline-rounded.svg';
import materialSymbolsShareOutline from 'src/assets/icons/material-symbols-share-outline.svg';
import mdiInvite from 'src/assets/icons/mdi-invite.svg';
import mdiSimOutline from 'src/assets/icons/mdi-sim-outline.svg';
import mdiSimOutline2 from 'src/assets/icons/mdi-sim-outline2.svg';
import menu from 'src/assets/icons/menu.svg';
import mingcuteGiftFill from 'src/assets/icons/mingcute-gift-fill.svg';
import mingcuteLinkLine from 'src/assets/icons/mingcute-link-line.svg';
import mingcuteRouterModemFill from 'src/assets/icons/mingcute-router-modem-fill.svg';
import minus from 'src/assets/icons/minus.svg';
import mnpBig from 'src/assets/icons/mnp-big.svg';
import mnp from 'src/assets/icons/mnp.svg';
import modalV from 'src/assets/icons/modal-v.svg';
import modalX from 'src/assets/icons/modal-x.svg';
import mufg from 'src/assets/icons/mufg.svg';
import myOrders from 'src/assets/icons/my-orders.svg';
import myPayment from 'src/assets/icons/my-payment.svg';
import myPurchases from 'src/assets/icons/my-purchases.svg';
import myRequestListPersonal from 'src/assets/icons/my-request-list-personal.svg';
import myRequestList from 'src/assets/icons/my-request-list.svg';
import noImage from 'src/assets/icons/no-image.svg';
import nonCheckV from 'src/assets/icons/non-check-v.svg';
import noticeCircle from 'src/assets/icons/notice-circle.svg';
import notificationAlert from 'src/assets/icons/notification-alert.svg';
import notification from 'src/assets/icons/notification.svg';
import order from 'src/assets/icons/order.svg';
import payPay from 'src/assets/icons/pay-pay.svg';
import paymentMonthlyFee from 'src/assets/icons/payment-monthly-fee.svg';
import paypay from 'src/assets/icons/paypay.svg';
import personalMyOrders from 'src/assets/icons/personal-my-orders.svg';
import personal from 'src/assets/icons/personal.svg';
import plus from 'src/assets/icons/plus.svg';
import pointBlank from 'src/assets/icons/point-blank.svg';
import pointExpired from 'src/assets/icons/point-expired.svg';
import pointGiftPoint from 'src/assets/icons/point-gift-point.svg';
import pointNewRegister from 'src/assets/icons/point-new-register.svg';
import pointOrder from 'src/assets/icons/point-order.svg';
import pointPaymentBronze from 'src/assets/icons/point-payment-bronze.svg';
import pointPaymentDiamond from 'src/assets/icons/point-payment-diamond.svg';
import pointPaymentGold from 'src/assets/icons/point-payment-gold.svg';
import pointPaymentSilver from 'src/assets/icons/point-payment-silver.svg';
import pointPayment from 'src/assets/icons/point-payment.svg';
import pointRefer from 'src/assets/icons/point-refer.svg';
import pointReturnPoint from 'src/assets/icons/point-return-point.svg';
import privacyPolicy from 'src/assets/icons/privacy-policy.svg';
import privacy from 'src/assets/icons/privacy.svg';
import profileEdit from 'src/assets/icons/profile-edit.svg';
import provideDoc from 'src/assets/icons/provide-doc.svg';
import qrCorner from 'src/assets/icons/qr-corner.svg';
import qrEsim from 'src/assets/icons/qr-esim.svg';
import question from 'src/assets/icons/question.svg';
import radioCheckedBordered from 'src/assets/icons/radio-checked-bordered.svg';
import radioChecked from 'src/assets/icons/radio-checked.svg';
import radioUncheckedFilled from 'src/assets/icons/radio-unchecked-filled.svg';
import radioUnchecked from 'src/assets/icons/radio-unchecked.svg';
import rakuten from 'src/assets/icons/rakuten.svg';
import refresh from 'src/assets/icons/refresh.svg';
import requestDevice from 'src/assets/icons/request-device.svg';
import router from 'src/assets/icons/router.svg';
import routt from 'src/assets/icons/routt.svg';
import scan from 'src/assets/icons/scan.svg';
import send from 'src/assets/icons/send.svg';
import settings from 'src/assets/icons/settings.svg';
import share2 from 'src/assets/icons/share-2.svg';
import share from 'src/assets/icons/share.svg';
import shippingBox from 'src/assets/icons/shipping-box.svg';
import shipping from 'src/assets/icons/shipping.svg';
import shop from 'src/assets/icons/shop.svg';
import silverMember from 'src/assets/icons/silver-member.svg';
import sim from 'src/assets/icons/sim.svg';
import smartpit from 'src/assets/icons/smartpit.svg';
import softbank from 'src/assets/icons/softbank.svg';
import solarStarLineDuotone from 'src/assets/icons/solar-star-line-duotone.svg';
import starFilled from 'src/assets/icons/star-filled.svg';
import starOutlined from 'src/assets/icons/star-outlined.svg';
import startBlue from 'src/assets/icons/start-blue.svg';
import start1 from 'src/assets/icons/start1.svg';
import store from 'src/assets/icons/store.svg';
import suggestions from 'src/assets/icons/suggestions.svg';
import supportChatBubble from 'src/assets/icons/support-chat-bubble.svg';
import tabBarBump from 'src/assets/icons/tab-bar-bump.svg';
import takePhoto from 'src/assets/icons/take-photo.svg';
import techSupport from 'src/assets/icons/tech-support.svg';
import termsOfUse from 'src/assets/icons/terms-of-use.svg';
import terms from 'src/assets/icons/terms.svg';
import thinWhiteX from 'src/assets/icons/thin-white-x.svg';
import transactionHistory from 'src/assets/icons/transaction-history.svg';
import transfer from 'src/assets/icons/transfer.svg';
import trashcan from 'src/assets/icons/trashcan.svg';
import uilCreditCard from 'src/assets/icons/uil-credit-card.svg';
import upVec from 'src/assets/icons/up-vec.svg';
import uploadPhoto from 'src/assets/icons/upload-photo.svg';
import userAvatar from 'src/assets/icons/user-avatar.svg';
import walletCreditCard from 'src/assets/icons/wallet-credit-card.svg';
import walletUnpaid from 'src/assets/icons/wallet-unpaid.svg';
import whiteX from 'src/assets/icons/white-x.svg';
import x from 'src/assets/icons/x.svg';

export const ICONS = {
  accountInfo,
  addContract,
  addOutlineGrey,
  addOutline,
  addPic,
  additionalInfo,
  arrowUp,
  au,
  avatarEdit,
  bronzeMember,
  calendar,
  camera,
  cancelOrder,
  cardCornerWide,
  cardCorner,
  cart,
  ccGi,
  changePassword,
  changePaymentMethod,
  checkDataCapacity,
  checkNetworkSpeed,
  checkV,
  check,
  checkboxChecked,
  checkboxUnchecked,
  chevronDownAlt,
  chevronDown,
  chevronLeft,
  chevronRightAlt,
  chevronRight,
  circlePlus,
  clarityListLine,
  clipboard,
  closeGray,
  closeRound,
  closeWhite,
  cod,
  combini,
  contactSupportPersonal,
  contactSupport,
  contact,
  contractOutline,
  contract,
  counter,
  creditLogo,
  credit,
  dataCharge,
  dcom,
  deleteAccount,
  diamondMember,
  docomo,
  doneSelected,
  doneUnselected,
  dotSee,
  dotsHorizontal,
  dots,
  dowVec,
  downloadConfig,
  download,
  dropdowTai,
  editable,
  epWarnTriangleFilled,
  esimBig,
  esim,
  eventGift,
  eyeClosed,
  eye,
  faceScanOverlay,
  feNoticePush,
  female,
  flashOn,
  fluentDataPie20Regular,
  fluentOptions48Filled,
  fluentTableSimpleInclude16Regular,
  ggList,
  goldMember,
  gridLayout,
  history,
  home,
  iconParkOutlinePaperMoney,
  iconPointPayment,
  icons8Plus,
  image,
  infinity,
  info,
  invite,
  ionFilter,
  jpBank,
  languageChecked,
  languageUnchecked,
  language,
  law,
  letsIconsCreditCard,
  linkOut,
  listLayout,
  location,
  logOut,
  majesticonsDataPlusLine,
  male,
  managePaymentMethods,
  materialSymbolsCampaignOutlineRounded,
  materialSymbolsCardMembershipOutline,
  materialSymbolsDeleteOutline,
  materialSymbolsMarkChatUnreadOutlineRounded,
  materialSymbolsShareOutline,
  mdiInvite,
  mdiSimOutline,
  mdiSimOutline2,
  menu,
  mingcuteGiftFill,
  mingcuteLinkLine,
  mingcuteRouterModemFill,
  minus,
  mnpBig,
  mnp,
  modalV,
  modalX,
  mufg,
  myOrders,
  myPayment,
  myPurchases,
  myRequestListPersonal,
  myRequestList,
  noImage,
  nonCheckV,
  noticeCircle,
  notificationAlert,
  notification,
  order,
  payPay,
  paymentMonthlyFee,
  paypay,
  personalMyOrders,
  personal,
  plus,
  pointBlank,
  pointExpired,
  pointGiftPoint,
  pointNewRegister,
  pointOrder,
  pointPaymentBronze,
  pointPaymentDiamond,
  pointPaymentGold,
  pointPaymentSilver,
  pointPayment,
  pointRefer,
  pointReturnPoint,
  privacyPolicy,
  privacy,
  profileEdit,
  provideDoc,
  qrCorner,
  qrEsim,
  question,
  radioCheckedBordered,
  radioChecked,
  radioUncheckedFilled,
  radioUnchecked,
  rakuten,
  refresh,
  requestDevice,
  router,
  routt,
  scan,
  send,
  settings,
  share2,
  share,
  shippingBox,
  shipping,
  shop,
  silverMember,
  sim,
  smartpit,
  softbank,
  solarStarLineDuotone,
  starFilled,
  starOutlined,
  startBlue,
  start1,
  store,
  suggestions,
  supportChatBubble,
  tabBarBump,
  takePhoto,
  techSupport,
  termsOfUse,
  terms,
  thinWhiteX,
  transactionHistory,
  transfer,
  trashcan,
  uilCreditCard,
  upVec,
  uploadPhoto,
  userAvatar,
  walletCreditCard,
  walletUnpaid,
  whiteX,
  x,
};
