//
// DO NOT EDIT! This is an autogenerated file.
//

import bg from 'src/assets/images/bg.png';
import loginBackground from 'src/assets/images/login-background.png';

export const IMAGES = {
  bg,
  loginBackground,
};
