//
// DO NOT EDIT! This is an autogenerated file.
//

import bannerDemo from 'src/assets/images/banner-demo.png';
import bgItem from 'src/assets/images/bg-item.png';
import bg from 'src/assets/images/bg.png';
import bronzeMember from 'src/assets/images/bronze-member.png';
import buyData from 'src/assets/images/buy-data.png';
import combiniLogos from 'src/assets/images/combini-logos.png';
import copyEidAndroidStep1 from 'src/assets/images/copy-eid-android-step1.png';
import copyEidAndroidStep2 from 'src/assets/images/copy-eid-android-step2.png';
import copyEidAndroidStep3 from 'src/assets/images/copy-eid-android-step3.png';
import copyEidAndroidStep4 from 'src/assets/images/copy-eid-android-step4.png';
import copyEidIphoneStep1 from 'src/assets/images/copy-eid-iphone-step1.png';
import copyEidIphoneStep2 from 'src/assets/images/copy-eid-iphone-step2.png';
import copyEidIphoneStep3 from 'src/assets/images/copy-eid-iphone-step3.png';
import copyEidIphoneStep4 from 'src/assets/images/copy-eid-iphone-step4.png';
import diamondMember from 'src/assets/images/diamond-member.png';
import goldMember from 'src/assets/images/gold-member.png';
import joinTheEvent from 'src/assets/images/join-the-event.png';
import qrDowload from 'src/assets/images/qr-dowload.png';
import qrEsim from 'src/assets/images/qr-esim.png';
import silverMember from 'src/assets/images/silver-member.png';
import step1mm from 'src/assets/images/step1mm.png';
import step2mm from 'src/assets/images/step2mm.png';
import step3mm from 'src/assets/images/step3mm.png';
import supportChatBubbleFlash from 'src/assets/images/support-chat-bubble-flash.png';
import supportChatBubble from 'src/assets/images/support-chat-bubble.png';
import tconnectApple from 'src/assets/images/tconnect-apple.png';
import tconnectFacebook1 from 'src/assets/images/tconnect-facebook1.png';
import tconnectGoogle from 'src/assets/images/tconnect-google.png';
import tconnectLogo2 from 'src/assets/images/tconnect-logo-2.png';
import tconnectLogoChat from 'src/assets/images/tconnect-logo-chat.png';
import tconnectLogoQr from 'src/assets/images/tconnect-logo-qr.png';
import tconnectLogo from 'src/assets/images/tconnect-logo.png';
import tconnectZalo from 'src/assets/images/tconnect-zalo.png';
import updateMascot from 'src/assets/images/update-mascot.png';

export const IMAGES = {
  bannerDemo,
  bgItem,
  bg,
  bronzeMember,
  buyData,
  combiniLogos,
  copyEidAndroidStep1,
  copyEidAndroidStep2,
  copyEidAndroidStep3,
  copyEidAndroidStep4,
  copyEidIphoneStep1,
  copyEidIphoneStep2,
  copyEidIphoneStep3,
  copyEidIphoneStep4,
  diamondMember,
  goldMember,
  joinTheEvent,
  qrDowload,
  qrEsim,
  silverMember,
  step1mm,
  step2mm,
  step3mm,
  supportChatBubbleFlash,
  supportChatBubble,
  tconnectApple,
  tconnectFacebook1,
  tconnectGoogle,
  tconnectLogo2,
  tconnectLogoChat,
  tconnectLogoQr,
  tconnectLogo,
  tconnectZalo,
  updateMascot,
};
