#!/usr/bin/env sh

changed () {
    git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

if changed 'yarn.lock'; then
    echo "yarn.lock changed. Running 'yarn install' to bring your dependencies up to date..."
    yarn install
fi

exit 0
